### ISSUE TITLE
[BUG] Camera doesn't work in Chrome on Windows 

### ISSUE THREAD

**Issue by marmata** [l4rm4nd/VoucherVault#42]
**Describe the bug**
When I create a new itemand click on the camera icon on the Redeem code field, I get an error "Unable to access video stream: Requested device not found"

**Affected version**
1.7.3

**To Reproduce**
1. Go to "Create New Item" using Chrome on Windows
2. Click on the camera icon beside the "Redeem Code" field
3. Watch the error

**Expected behavior**
It should ask for permission to use camera, and then error out if not given.

**Screenshots**
![image](https://github.com/user-attachments/assets/27b8f7ec-2783-42a8-ae05-70df592a57b0)

**Additional context**
I also tried to give explicit consent to the webpage for camera, same error. VoucherVault is behind a reverse proxy using https.

**Comment by l4rm4nd** [comment]
1. Clear site permissions and cache; may try incognito mode
2. Try a different browser like Firefox

Ensure you have a webcam connected of course.

**Comment by marmata** [comment]
I was dumb, didn't realize the camera was disconnected! However another issue. I cannot from the life of me making VoucherVault recognize any EAN13 code, either on chrome with my webcam or on iOS with Safari. Nothing gets detected. On iOS after some tries a made up code appears in the field: 121834730525623 (code to be scanned is ++623135406). Is there something special that needs to be done?

**Comment by l4rm4nd** [comment]
> I was dumb, didn't realize the camera was disconnected! However another issue. I cannot from the life of me making VoucherVault recognize any EAN13 code, either on chrome with my webcam or on iOS with Safari. Nothing gets detected. On iOS after some tries a made up code appears in the field: 121834730525623 (code to be scanned is ++623135406). Is there something special that needs to be done?

https://github.com/l4rm4nd/VoucherVault/wiki/04-%E2%80%90-Application-Usage#creating-items

There is a known bug in chrome-based browsers. Those will select a weird wide-angle camera, which cannot focus properly and scan codes successfully.

This affects only a few browsers. Typically mobile browsers. Is a chrome issue and won't be fixed in the upstream library. So I won't fix too.

May try a different browser like Firefox. It implements the JavaScript's `getMediaType` correctly.

**Comment by marmata** [comment]
Fantastic, thanks! I still have some issues with Safari on iPhone which should not be affected by the above. I'll try with some other cards, thanks!
